In [2]:
import time
import numpy as np
import torch
import os
os.environ ["KMP_DUPLICATE_LIB_OK"] ="TRUE"
# 定义矩阵的大小
matrix_size = (10000, 10000)

# 生成随机矩阵
np_matrix1 = np.random.rand(*matrix_size)
np_matrix2 = np.random.rand(*matrix_size)

# NumPy CPU矩阵乘法
start_time = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
cpu_time = end_time - start_time

# 将NumPy矩阵转换为PyTorch张量，并将其移动到GPU上（如果可用）
torch_matrix1 = torch.tensor(np_matrix1)
torch_matrix2 = torch.tensor(np_matrix2)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch_matrix1 = torch_matrix1.to(device)
torch_matrix2 = torch_matrix2.to(device)

# PyTorch GPU矩阵乘法
start_time = time.time()
torch_result = torch.mm(torch_matrix1, torch_matrix2)
end_time = time.time()
gpu_time = end_time - start_time

# 输出结果
print(f"NumPy CPU 矩阵乘法耗时：{cpu_time:.6f} 秒")
print(f"PyTorch GPU 矩阵乘法耗时：{gpu_time:.6f} 秒")


NumPy CPU 矩阵乘法耗时：4.253963 秒
PyTorch GPU 矩阵乘法耗时：0.011390 秒


In [16]:
# data = {
#     'Name': ['Alice', 'Bob', 'Charlie'],
#     'Age': [25, None, 35],
#     'Salary': [1, 2, 3]
# }

# df = pd.DataFrame(data)

# x = df.dtypes[df.dtypes != 'object'].index

# df[x] =  df[x].fillna(0)
# df[x]
# df[x].fillna(0)
# df


test_list = ['a','b','c']
a = 1 
test_list[0] 




Age  Salary
0  25.0       1
1   0.0       2
2  35.0       3

In [1]:
import socket
# 1.创建socket
tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# 2. 链接服务器
server_addr = ("61.139.65.141", 50461)
tcp_socket.connect(server_addr)

# 3. 发送数据
send_data = input("请输入要发送的数据：")
tcp_socket.send(send_data.encode("gbk"))

# 4. 关闭套接字
tcp_socket.close()

In [1]:
import torch
x = torch.zeros((2,3))
print(x.shape)


torch.Size([2, 3])


In [2]:
X = torch.arange(1,25).reshape(3,8)
for t  in X:
    print(t)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([ 9, 10, 11, 12, 13, 14, 15, 16])
tensor([17, 18, 19, 20, 21, 22, 23, 24])


In [16]:
X = torch.arange(1,121).reshape(2,3,4,5)
Y = torch.rand(2,3)
Z = torch.rand(4,5)
out = torch.matmul(X,Y,Z)

TypeError: matmul() takes 2 positional arguments but 3 were given

$||A||F = √(ΣΣ |a_ij|^2)$