## 1 标量

数学上的常量

## 2 向量

多个标量有序排列，排成一列为列向量，排成一行为行向量。机器学习当中默认是列向量，
由于表示等问题，一般写成行向量的转置形式。

## 3 矩阵
多个行向量/列向量构成的矩阵，也称之为张量。

## 4 一些计算

### 4.1 矩阵元素对应位置相乘，作为对应位置的结果
称之为Hadamard积
![](https://raw.githubusercontent.com/SisyphusTang/Picture-bed/master/image-20230716214556820.png)

In [3]:
import torch
A = torch.ones(2,3)
B = torch.ones(2,3)
A *= 2
B *= 2
A,B

(tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]))

In [4]:
A*B

tensor([[4., 4., 4.],
        [4., 4., 4.]])

### 4.2 降维

让矩阵沿着某一轴进行求和，结果这一轴就被消除掉了，以达到降维的作用。
当然，**也可以让原数组的维度不发生变化，只要在后面加上keepdims=True即可。**

### 4.3 点积（Dot Product）
这里不介绍向量与向量、矩阵与向量，直接介绍矩阵与矩阵的点积。
![](https://raw.githubusercontent.com/SisyphusTang/Picture-bed/master/image-20230716215341521.png)

矩阵A的行乘以矩阵B的列的和作为对应位置的值。
![](https://raw.githubusercontent.com/SisyphusTang/Picture-bed/master/image-20230716215651950.png)

In [6]:
B = torch.ones(3,2)
B *= 2
torch.mm(A,B)

tensor([[12., 12.],
        [12., 12.]])

### 4.4 范数（新接触的概念）

#### L1范数与L2范数
简单来说，L1范数就是向量所有元素的绝对值求和，L2范数是所有元素的平方和开根号。
公式如下：
![](https://raw.githubusercontent.com/SisyphusTang/Picture-bed/master/image-20230716220036126.png)
![](https://raw.githubusercontent.com/SisyphusTang/Picture-bed/master/image-20230716220102179.png)

#### 矩阵的Frobenius范数 是矩阵元素平方和的平方根
![](https://raw.githubusercontent.com/SisyphusTang/Picture-bed/master/image-20230716220236568.png)

In [10]:
# 矩阵A的L1范数
t = torch.abs(A).sum()
t
# 矩阵A的L2范数
t = torch.norm(A)
t
# 矩阵的Frobenius范数
t = torch.norm(A)
t

tensor(4.8990)