# 线性代数

In [3]:
import torch
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [3]:
B = A.T
B

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵（symmetric matrix) A = A^^T

In [4]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [5]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [6]:
t1 = torch.arange(24).reshape(3,8)
t1

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])

In [7]:
print(B[0])

tensor([1, 2, 3])


In [11]:
t2 = torch.arange(24).reshape(2,3,4)
t2

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [22]:
print(t2[0][0][0],t2[0][1][0],t2[0][2][0])

tensor(0) tensor(4) tensor(8)


python三层数组可以作如下理解：
https://blog.csdn.net/WalkerTC/article/details/131736504

In [25]:
tmp = torch.ones((2,3,4),dtype=int)
tmp

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

维度求和sum函数

In [30]:
t = tmp.sum(axis=0)   # 纵轴求和
print(t)
t = tmp.sum(axis = 1) # 第二个维度求和 每一行求和
print(t)
t = tmp.sum(axis = 2) # 第三个维度求和 每一个面的每一行求和
print(t)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])
tensor([[3, 3, 3, 3],
        [3, 3, 3, 3]])
tensor([[4, 4, 4],
        [4, 4, 4]])


## 按照特定轴求和

上述按照三维空间对于轴求和理解遇到多维比较难想象，对于按轴求和，按照哪一轴其实就是
消去某一轴，保留剩下轴的结果，如上述图按axis = 0求和，求和之后的数组就是(3,4)shape的，
按照axis = 1的，就是（2，3）shape形状的，同理，axis = 2就是（2，3）shape的结果

![jupyter](https://cdn.staticaly.com/gh/SisyphusTang/Picture-bed@master/20230715/py三维数组.708d7ri0m1g0.webp)

学习其它算法或者框架都没关系，主要是学会。
date:2023-07-15