In [4]:
import tensorflow as tf
import numpy as np

t = np.array([1,2.,3,3]) 
x = tf.constant(t)
print(x)
# 通过numpy转换为其它格式 以供系统其它地方的使用
print(x.numpy())

tmp = tf.ones((2,3))
print(tmp)

tf.Tensor([1. 2. 3. 3.], shape=(4,), dtype=float64)
[1. 2. 3. 3.]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [5]:
tf.random.normal(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.48654708, -0.12080303,  0.273296  ,  0.03670556],
       [-0.5934348 ,  0.3364384 ,  0.38190484,  0.0982357 ],
       [ 0.6805319 , -2.107822  , -0.340298  , -0.6644541 ]],
      dtype=float32)>

In [6]:
x = tf.random.uniform((2,3), 0, 7, dtype=tf.float32)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4.862332 , 5.663393 , 4.7601314],
       [3.2441087, 3.212919 , 2.2959228]], dtype=float32)>

In [11]:
out = tf.random.uniform([4, 10])
y = tf.constant([2, 3, 2, 0])
y = tf.one_hot(y, depth=10)
# print(out)
loss = tf.keras.losses.mse(y,out)
t = loss.numpy()
t /= 4
print(sum(t))
loss = tf.reduce_mean(loss)
print(loss)

0.31538717821240425
tf.Tensor(0.3153872, shape=(), dtype=float32)


In [ ]:
fc = layers.